INFERANALYZE = '/home/cs4278/hw/cs4278-hw04/downloads/infer-linux64-v0.13.0/infer/bin/infer-analyze' --no-report --results-dir '/home/cs4278/hw/cs4278-hw04/downloads/lighttpd-1.4.17/infer-out' 

CLUSTERS=

default: test

all: test

test: $(CLUSTERS)
	@echo


clean:
	rm -f $(CLUSTERS)
